site_name: TAMU Plant Genomics
theme:
  name: readthedocs

nav:
  - Home: index.md
  - HPRC:
      - Overview: hprc/overview.md
      - Getting Started: hprc/getting_started.md
      - Data Resources: hprc/data_resources.md
      - Conda Environments: hprc/conda_env.md
      - Slurm Support: hprc/slurm_support.md
  - Analysis:
      - Overview: analysis/overview.md
      - Tools:
        - Overview: analysis/tools.md
        - myrs: analysis/myrs.md
        - svmarkers: analysis/svmarkers.md
      - Pipelines:
        - Overview: analysis/pipelines.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - ezlinks

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/contrib/auto-render.min.js
  - js/katex.js